# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='model',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
