# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_auto_20180323_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
